/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public int addition(int a, int b) {
        return a + b;
    }

    public int divide(int a, int b) throws ArithmeticException{
        return a / b;
    }

    public int multiply(int a , int b) {
        return a * b;
    }

    private boolean validator(char ch) {
        return (Character.isLetterOrDigit(ch));
    }

    public boolean isPalindrome(String str) {
        String newS = str.toLowerCase().trim();
        if (newS.length() < 2)
            return true;
        int left = 0,
            right = newS.length()-1;
        while (left < right) {
            if ((
                    !validator(newS.charAt(left)) || !validator(newS.charAt(right))
                )
                || newS.charAt(left) != newS.charAt(right)
            )
                return false;
            left++;
            right--;
        }
        return true;
    }

    public boolean Positive(int a) {
        return (a > 0);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
