/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

class calculator {
    protected float addition(int a, int b) {
        return a + b;
    }

    protected float subtraction(int a, int b) {
        return a - b;
    }
    
    protected float multiplication(int a, int b) {
        return a * b;
    }

    protected float division(int a, int b) {
        float res = 0.0f;
        try {
            res = (float)a / b;
        }catch(ArithmeticException e) {
            System.out.println(e.getMessage());
        }
        return res;
    }
}

public class App extends calculator{
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
