/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class AppTest {

    App obj = new App();

    @Test
    @BeforeEach
    void initTheObject() {
        obj = new App();
        System.out.println("Intitalized the object");
    }

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void checkTheFunctionality() {
        assertEquals(3, obj.addition(1, 2), "CORRECT");
        assertEquals(2, obj.division(4, 2), "CORRECT");
    }
}
