/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package learning;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    
    @Test
    @DisplayName("test for addition")
    void appAdditionTest() {
        App obj = new App();
        assertEquals(5, obj.addition(3, 2), "ERR: 3 + 2 != 5");
    }
}
