/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myApp;

import lib.Process;

import java.util.Scanner;

public class App extends Process {


    public App(String sss) {
        super(sss);
    }

    public App() {}

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Process[] obj = new Process[10];
//        if (obj[0] == null)
//            System.out.println("not initialized");

        for (int i = 0; i < 10; i++) {
            System.out.println("Enter name for the process");
            String ss = in.nextLine();
            obj[i] = new App(ss);
        }

        for (int i = 0; i < 10; i++) {
            obj[i].getInfo();
            System.out.println("--------------");
        }
        in.close();
    }
}
